/**
 * Caddyfile generator
 *
 * Generate complete Caddyfile with routes for all services.
 */

import type { Intent } from "@dldc/tower/types";
import { logger } from "../utils/logger.ts";

/**
 * Generate Caddyfile content
 */
export function generateCaddyfile(intent: Intent): string {
  logger.info("Generating Caddyfile...");

  const blocks: string[] = [];

  // Global config
  blocks.push(generateGlobalConfig(intent));

  // Registry block (with auth on write operations)
  blocks.push(generateRegistryBlock(intent));

  // Tower block (with Basic Auth)
  blocks.push(generateTowerBlock(intent));

  // OTEL block (Grafana dashboard)
  blocks.push(generateOtelBlock(intent));

  // App blocks
  for (const app of intent.apps) {
    blocks.push(generateAppBlock(app));
  }

  return `# Generated by Tower - Do not edit manually\n\n${blocks.join("\n\n")}`;
}

/**
 * Generate global Caddy configuration
 */
function generateGlobalConfig(intent: Intent): string {
  return `{
  email ${intent.adminEmail}
}`;
}

/**
 * Generate registry route block
 */
function generateRegistryBlock(intent: Intent): string {
  return `${intent.registry.domain} {
  # Registry access - Basic Auth on write operations
  @write {
    method POST PUT PATCH DELETE
    path /v2/*
  }

  handle @write {
    basic_auth {
      # Credentials from /var/infra/credentials.json
      # TODO: Load dynamically during Caddy startup
      ci JDJhJDEwJFJLTUVSbWNhYTdITmxLVGRIbmw5T2VYRkhMbk5VRmxLUnl3T3FIczBZVEJhaG9wdzh5b01DCg==
    }
    reverse_proxy registry:5000
  }

  # Read operations (GET) - no auth required
  reverse_proxy registry:5000
}`;
}

/**
 * Generate Tower route block
 */
function generateTowerBlock(intent: Intent): string {
  return `${intent.tower.domain} {
  basic_auth {
    # Credentials from /var/infra/credentials.json
    # TODO: Load dynamically during Caddy startup
    tower JDJhJDEwJFJLTUVSbWNhYTdITmxLVGRIbmw5T2VYRkhMbk5VRmxLUnl3T3FIczBZVEJhaG9wdzh5b01DCg==
  }
  reverse_proxy tower:3100
}`;
}

/**
 * Generate OTEL-LGTM route block
 */
function generateOtelBlock(intent: Intent): string {
  return `${intent.otel.domain} {
  reverse_proxy otel-lgtm:3000
}`;
}

/**
 * Generate app route block
 */
function generateAppBlock(app: { name: string; domain: string; port?: number }): string {
  const port = app.port ?? 3000;
  return `${app.domain} {
  reverse_proxy ${app.name}:${port}
}`;
}

/**
 * Extract all domains from intent
 */
export function extractDomains(intent: Intent): string[] {
  return [
    intent.tower.domain,
    intent.registry.domain,
    intent.otel.domain,
    ...intent.apps.map((app) => app.domain),
  ];
}
